name: updateJekyllContent
on:
   workflow_dispatch:
   # push:
   #   branches:
   #     - main
   # schedule:
   # - cron: '54 0 * * *' # 每天 UTC 0:00 执行

jobs:
  generate-hot-topics:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Generate Hot Topics Markdown
        run: node updateJekyllContent.js
      - name: Set commit message
        id: commit
        run: |
          # Array of 10 commit messages
          commit_messages=("内容获取最新" "实时获取热点数据" "获取24小时数据" "把最新内容展示在前面" "实时热点备份" "当前日期的热点备份" "暂无热点可以向下获取最新" "把最新文件替换掉" "实时更新数据" "最后一次备份")
          # Get a random index to select a commit message from the array
          random_index=$(( RANDOM % 10 ))
          # Retrieve the selected commit message
          selected_commit_message="${commit_messages[$random_index]}"
          # Add the commit message to the commit message file
          echo "$selected_commit_message" > commit_message.txt
          
      - name: Commit and push changes
        run: |
          git config --local user.email "pingbeer69@gmail.com"
          git config --local user.name "logep"

          git add . -- :^node_modules/
          git commit -m "$(cat commit_message.txt)"
          git push -f
